### PR TITLE
Fixed identifier of bound functions on node 4

### PR DESCRIPTION
**Pull request by jordansexton**
Originally detected while using [co-redis](/mciparelli/co-redis); thenify breaks libraries that depend on it when using Node 4.x and bound functions are passed to `eval`/`createWrapper`.

This is because the function name `'bound '` contains a space, making it an illegal identifier.

This commit fixes this in accordance with [the same fix here](https://github.com/nodejs/node/issues/2798#issuecomment-140059017).

### CODE REVIEW

**Comment by jonathanong** [comment]
can you add a test?

**Comment by jordansexton** [comment]
There seems to be a problem with Travis relating to node 0.8, but here is the test output after all commits in this PR:

```
➜  thenify git:(patch-1) npm test

> thenify@3.1.0 test /Users/jordan/Projects/thenify
> mocha --reporter spec



  ✓ fn.name
  ✓ fn.name (bound function)
  ✓ fn(callback(err))
  ✓ fn(callback(null, value))
  ✓ fn(callback(null, values...))
  ✓ fn(..args, callback())
  Promisify
    ✓ should reject errors
    ✓ should reject errors with arguments
    ✓ should return the result

  with callback backward compatible
    fn.name
      ✓ should set function name by default
      ✓ should set name to empty
    fn(callback(err)
      ✓ promise
      ✓ callback
    fn(callback(null, value))
      ✓ promise
      ✓ callback
    fn(callback(null, values...))
      ✓ promise
      ✓ callback
    fn(..args, callback())
      ✓ promise
      ✓ callback


  19 passing (25ms)
```

**Comment by jonathanong** [comment]
oh feel free to remove `0.8` from travis. we don't need to support it anymore.

**Comment by jordansexton** [comment]
Not sure how you like commits structured, but I can squash these if desired.

**Comment by jonathanong** [comment]
nope these are great because your commits names all make sense :+1:

**Comment by jonathanong** [comment]
merged 1a26a740a0d892ca73ce99a47ae2fb679b7b8418

**Comment by EugeneBakin** [comment]
Hi, is there a reason why this problem have not been fixed for "withCallback" version?

**Comment by coderhaoxin** [comment]
need a PR, 😢  ((^_^))

**Comment by dead-horse** [comment]
fixed in acdcd59de41ee1148659c5db6b154fafa4c1b2d3

**Comment by EugeneBakin** [comment]
thank you

**Pull request closed without merging**
